### ISSUE TITLE
htdigest auth

### ISSUE THREAD

**Issue by sammcj** [frlen/nagnu#3]
Hi,

This doesn't seem to work with htdigest auth?

**Comment by frlen** [comment]
Hi

I've never tested digest auth but I will set a server up this weekend and try it out.

Curl is configured to use CURLAUTH_ANY which should cover digest authentication according to the documentation: https://curl.haxx.se/libcurl/c/CURLOPT_HTTPAUTH.html

You can try changing line 112 in nagnu.c to say CURLAUTH_DIGEST instead of CURLAUTH_ANY and see if it makes a difference.

**Comment by sammcj** [comment]
Yep that did it - thank you, do you think you'd be able to make it a config option?

**Comment by frlen** [comment]
Alright, excellent. Absolutely, I will make it a config option.

**Comment by sammcj** [comment]
Legend!

**Comment by frlen** [comment]
As of commit c7e65fc you can now use digest yes in nagnu.conf for digest authentication.

**Comment by sammcj** [comment]
Fantastic, thank you so much!
