### ISSUE TITLE
Invert excludes

### ISSUE THREAD

**Issue by bderiso** [frlen/nagnu#4]
Is there way to, for example, only show Current Load service_description checks and nothing else?

Does the "exclude" option support expressions so that I could do a negative lookahead or something similar?

If not, can we get functionality for an "include" option?

This utility seems useful for scripting but I'd rather not have to maintain an exclude file of every service_description expect the one I want to take action on.

**Comment by frlen** [comment]
No, not really. Excludes does not support regular expressions, only exact matches.
I have thought about includes but decided not to do it because the same functionality can be achieved by setting up a new user in nagios with access only to the checks in question.
I'd be happy to accept a pull request though if someone wants to develop the feature.

For scripting I think you'd be better of directly parsing the output from the nagios wap interface instead of going via nagnu.
The address for the demo server would be:
http://nagiosadmin:nagiosadmin@nagioscore.demos.nagios.com/nagios/cgi-bin/statuswml.cgi?style=uprobs

If you haven't already you should also look into nagios event handlers, it can execute scripts on state changes.
